name:
  - DCAC
channels:
  - conda-forge
  - CogSci
  - anaconda
dependencies:
  - beautifulsoup4
  - blosc
  - bokeh
  - catboost
  - conda
  - conda-pack
  - dask
  - datamatrix
  - datashader
  - fastparquet
  - feather-format
  - gdown
  - gensim
  - h5py
  - html5lib
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - lxml
  - lz4
  - matplotlib
  - networkx
  - numba
  - numpy
  - openpyxl
  - pandas
  - pillow
  - plotly
  - pyarrow
  - pygwalker
  - python
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - snappy
  - statsmodels
  - xgboost
  - xlrd
  - xlwt
  - opensesame-core 
  - rapunzel 
  - opensesame-extension-osweb 
  - opensesame-extension-updater 
  - opensesame-plugin-psychopy 
  - opensesame-plugin-media_player_mpy
  - psychopy 
  - psychopy_sounddevice 
  - pygame 
  - http://files.cogsci.nl/expyriment-0.10.0+opensesame2-py3-none-any.whl 
  - https://github.com/smathot/PyGaze/releases/download/prerelease%2F0.8.0a3/python_pygaze-0.8.0a3-py3-none-any.whl
  
  