name:
  - DCAC
channels:
  - conda-forge
  - CogSci
  - anaconda
dependencies:
  - beautifulsoup4
  - blosc
  - bokeh
  - catboost
  - conda
  - conda-pack
  - dask
  - datamatrix
  - datashader
  - fastparquet
  - feather-format
  - gdown
  - gensim
  - h5py
  - html5lib
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - keras
  - lightgbm
  - lxml
  - lz4
  - matplotlib
  - multiprocess
  - mysql-connector-python
  - networkx
  - numba
  - numpy
  - opencv
  - openpyxl
  - pandas
  - pillow
  - plotly
  - psycopg2
  - pyarrow
  - python
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - snappy
  - spacy
  - sqlalchemy
  - sqlite
  - statsmodels
  - xgboost
  - xlrd
  - xlwt

 