name:
  - DCAC
channels:
  - conda-forge
  - CogSci
  - anaconda
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - xgboost
  - lightgbm
  - catboost
  - nltk
  - spacy
  - gensim
  - jupyter
  - jupyterlab
  - ipython
  - ipywidgets
  - bokeh
  - holoviews
  - datashader
  - dask
  - joblib
  - statsmodels
  - scikit-image
  - opencv
  - pillow
  - numba
  - networkx
  - sqlite
  - sqlalchemy
  - psycopg2
  - mysql-connector-python
  - h5py
  - requests
  - beautifulsoup4
  - lxml
  - html5lib
  - scrapy
  - graphviz
  - python-graphviz
  - python-Levenshtein
  - multiprocess
  - openpyxl
  - xlrd
  - xlwt
  - feather-format
  - pyarrow
  - fastparquet
  - snappy
  - lz4
  - blosc
  - conda-pack
  - conda=24.5.0
  - python=3.12.4
  - matplotlib
  - ipywidgets
  - nodejs
  - rpy2
  - datamatrix=1.0.13
  - r-base
  - r-tidyverse
  - r-ggplot2
  - r-shiny
  - r-foreign
  - r-dplyr
  - r-hmisc
  - jupyterlab-remote-contents
