name:
  - DCAC
channels:
  - conda-forge
  - CogSci
  - anaconda
dependencies:
  - beautifulsoup4
  - blosc
  - bokeh
  - catboost
  - conda
  - conda-pack
  - dask
  - datamatrix
  - datashader
  - fastparquet
  - feather-format
  - gdown
  - gensim
  - h5py
  - html5lib
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - lxml
  - lz4
  - matplotlib
  - networkx
  - numba
  - numpy
  - openpyxl
  - pandas
  - pillow
  - plotly
  - pyarrow
  - pygwalker
  - python
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - snappy
  - statsmodels
  - xgboost
  - xlrd
  - xlwt
  - absl-py                          
  - aiohttp                          
  - aiosignal                        
  - alabaster                        
  - albumentations                   
  - altair                           
  - annotated-types                  
  - anyio                            
  - appdirs                          
  - argon2-cffi                      
  - argon2-cffi-bindings             
  - array-record                     
  - arviz                            
  - astropy                          
  - astunparse                       
  - async-timeout                    
  - atpublic                         
  - attrs                            
  - audioread                        
  - autograd                         
  - Babel                            
  - backcall                         
  - beautifulsoup4                   
  - bidict                           
  - bigframes                        
  - bleach                           
  - blinker                          
  - blis                             
  - blosc2                           
  - bokeh                            
  - bqplot                           
  - branca                           
  - build                            
  - CacheControl                     
  - cachetools                       
  - catalogue                        
  - certifi                          
  - cffi                             
  - chardet                          
  - charset-normalizer               
  - chex                             
  - click                            
  - click-plugins                    
  - cligj                            
  - cloudpathlib                     
  - cloudpickle                      
  - cmake                            
  - cmdstanpy                        
  - colorcet                         
  - colorlover                       
  - colour                           
  - community                        
  - confection                       
  - cons                             
  - contextlib2                      
  - contourpy                        
  - cryptography                     
  - cufflinks                        
  - cupy-cuda12x                     
  - cvxopt                           
  - cvxpy                            
  - cycler                           
  - cymem                            
  - Cython                           
  - dask                             
  - datascience                      
  - db-dtypes                        
  - dbus-python                      
  - debugpy                          
  - decorator                        
  - defusedxml                       
  - distributed                      
  - distro                           
  - dlib                             
  - dm-tree                          
  - docutils                         
  - dopamine-rl                      
  - duckdb                           
  - earthengine-api                  
  - easydict                         
  - ecos                             
  - editdistance                     
  - eerepr                           
  - en-core-web-sm                   
  - entrypoints                      
  - et-xmlfile                       
  - etils                            
  - etuples                          
  - exceptiongroup                   
  - fastai                           
  - fastcore                         
  - fastdownload                     
  - fastjsonschema                   
  - fastprogress                     
  - fastrlock                        
  - filelock                         
  - fiona                            
  - firebase-admin                   
  - Flask                            
  - flatbuffers                      
  - flax                             
  - folium                           
  - fonttools                        
  - frozendict                       
  - frozenlist                       
  - fsspec                           
  - future                           
  - gast                             
  - gcsfs                            
  - GDAL                             
  - gdown                            
  - geemap                           
  - gensim                           
  - geocoder                         
  - geographiclib                    
  - geopandas                        
  - geopy                            
  - gin-config                       
  - glob2                            
  - google                           
  - google-ai-generativelanguage     
  - google-api-core                  
  - google-api-python-client         
  - google-auth                      
  - google-auth-httplib2             
  - google-auth-oauthlib             
  - google-cloud-aiplatform          
  - google-cloud-bigquery            
  - google-cloud-bigquery-connection 
  - google-cloud-bigquery-storage    
  - google-cloud-core                
  - google-cloud-datastore           
  - google-cloud-firestore           
  - google-cloud-functions           
  - google-cloud-iam                 
  - google-cloud-language            
  - google-cloud-resource-manager    
  - google-cloud-storage             
  - google-cloud-translate           
  - google-colab                     
  - google-crc32c                    
  - google-generativeai              
  - google-pasta                     
  - google-resumable-media           
  - googleapis-common-protos         
  - googledrivedownloader            
  - graphviz                         
  - greenlet                         
  - grpc-google-iam-v1               
  - grpcio                           
  - grpcio-status                    
  - gspread                          
  - gspread-dataframe                
  - gym                              
  - gym-notices                      
  - h5netcdf                         
  - h5py                             
  - holidays                         
  - holoviews                        
  - html5lib                         
  - httpimport                       
  - httplib2                         
  - huggingface-hub                  
  - humanize                         
  - hyperopt                         
  - ibis-framework                   
  - idna                             
  - imageio                          
  - imageio-ffmpeg                   
  - imagesize                        
  - imbalanced-learn                 
  - imgaug                           
  - importlib-metadata               
  - importlib-resources              
  - imutils                          
  - inflect                          
  - iniconfig                        
  - intel-openmp                     
  - ipyevents                        
  - ipyfilechooser                   
  - ipykernel                        
  - ipyleaflet                       
  - ipython                          
  - ipython-genutils                 
  - ipython-sql                      
  - ipytree                          
  - ipywidgets                       
  - itsdangerous                     
  - jax                              
  - jaxlib                           
  - jeepney                          
  - jieba                            
  - Jinja2                           
  - joblib                           
  - jsonpickle                       
  - jsonschema                       
  - jsonschema-specifications        
  - jupyter-client                   
  - jupyter-console                  
  - jupyter_core                     
  - jupyter-server                   
  - jupyterlab_pygments              
  - jupyterlab_widgets               
  - kaggle                           
  - kagglehub                        
  - keras                            
  - keyring                          
  - kiwisolver                       
  - langcodes                        
  - launchpadlib                     
  - lazr.restfulclient               
  - lazr.uri                         
  - lazy_loader                      
  - libclang                         
  - librosa                          
  - lightgbm                         
  - linkify-it-py                    
  - llvmlite                         
  - locket                           
  - logical-unification              
  - lxml                             
  - malloy                           
  - Markdown                         
  - markdown-it-py                   
  - MarkupSafe                       
  - matplotlib                       
  - matplotlib-inline                
  - matplotlib-venn                  
  - mdit-py-plugins                  
  - mdurl                            
  - miniKanren                       
  - missingno                        
  - mistune                          
  - mizani                           
  - mkl                              
  - ml-dtypes                        
  - mlxtend                          
  - more-itertools                   
  - moviepy                          
  - mpmath                           
  - msgpack                          
  - multidict                        
  - multipledispatch                 
  - multitasking                     
  - murmurhash                       
  - music21                          
  - natsort                          
  - nbclassic                        
  - nbclient                         
  - nbconvert                        
  - nbformat                         
  - nest-asyncio                     
  - networkx                         
  - nibabel                          
  - nltk                             
  - notebook                         
  - notebook_shim                    
  - numba                            
  - numexpr                          
  - numpy                            
  - oauth2client                     
  - oauthlib                         
  - opencv-contrib-python            
  - opencv-python                    
  - opencv-python-headless           
  - openpyxl                         
  - opt-einsum                       
  - optax                            
  - orbax-checkpoint                 
  - osqp                             
  - packaging                        
  - pandas                           
  - pandas-datareader                
  - pandas-gbq                       
  - pandas-stubs                     
  - pandocfilters                    
  - panel                            
  - param                            
  - parso                            
  - parsy                            
  - partd                            
  - pathlib                          
  - patsy                            
  - peewee                           
  - pexpect                          
  - pickleshare                      
  - Pillow                           
  - pins                             
  - pip                              
  - pip-tools                        
  - platformdirs                     
  - plotly                           
  - plotnine                         
  - pluggy                           
  - polars                           
  - pooch                            
  - portpicker                       
  - prefetch-generator               
  - preshed                          
  - prettytable                      
  - proglog                          
  - progressbar2                     
  - prometheus_client                
  - promise                          
  - prompt-toolkit                   
  - prophet                          
  - proto-plus                       
  - protobuf                         
  - psutil                           
  - psycopg2                         
  - ptyprocess                       
  - py-cpuinfo                       
  - py4j                             
  - pyarrow                          
  - pyarrow-hotfix                   
  - pyasn1                           
  - pyasn1-modules                   
  - pycocotools                      
  - pycparser                        
  - pyct                             
  - pydantic                         
  - pydantic_core                    
  - pydata-google-auth               
  - pydot                            
  - pydot-ng                         
  - pydotplus                        
  - PyDrive                          
  - PyDrive2                         
  - pyerfa                           
  - pygame                           
  - Pygments                         
  - PyGObject                        
  - PyJWT                            
  - pymc                             
  - pymystem3                        
  - PyOpenGL                         
  - pyOpenSSL                        
  - pyparsing                        
  - pyperclip                        
  - pyproj                           
  - pyproject_hooks                  
  - pyshp                            
  - PySocks                          
  - pytensor                         
  - pytest                           
  - python-apt                       
  - python-box                       
  - python-dateutil                  
  - python-louvain                   
  - python-slugify                   
  - python-utils                     
  - pytz                             
  - pyviz_comms                      
  - PyWavelets                       
  - PyYAML                           
  - pyzmq                            
  - qdldl                            
  - qudida                           
  - ratelim                          
  - referencing                      
  - regex                            
  - requests                         
  - requests-oauthlib                
  - requirements-parser              
  - rich                             
  - rpds-py                          
  - rpy2                             
  - rsa                              
  - safetensors                      
  - scikit-image                     
  - scikit-learn                     
  - scipy                            
  - scooby                           
  - scs                              
  - seaborn                          
  - SecretStorage                    
  - Send2Trash                       
  - sentencepiece                    
  - setuptools                       
  - shapely                          
  - six                              
  - sklearn-pandas                   
  - smart-open                       
  - sniffio                          
  - snowballstemmer                  
  - sortedcontainers                 
  - soundfile                        
  - soupsieve                        
  - soxr                             
  - spacy                            
  - spacy-legacy                     
  - spacy-loggers                    
  - Sphinx                           
  - sphinxcontrib-applehelp          
  - sphinxcontrib-devhelp            
  - sphinxcontrib-htmlhelp           
  - sphinxcontrib-jsmath             
  - sphinxcontrib-qthelp             
  - sphinxcontrib-serializinghtml    
  - SQLAlchemy                       
  - sqlglot                          
  - sqlparse                         
  - srsly                            
  - stanio                           
  - statsmodels                      
  - sympy                            
  - tables                           
  - tabulate                         
  - tbb                              
  - tblib                            
  - tenacity                         
  - tensorboard                      
  - tensorboard-data-server          
  - tensorflow                       
  - tensorflow-datasets              
  - tensorflow-estimator             
  - tensorflow-gcs-config            
  - tensorflow-hub                   
  - tensorflow-io-gcs-filesystem     
  - tensorflow-metadata              
  - tensorflow-probability           
  - tensorstore                      
  - termcolor                        
  - terminado                        
  - text-unidecode                   
  - textblob                         
  - tf-keras                         
  - tf-slim                          
  - thinc                            
  - threadpoolctl                    
  - tifffile                         
  - tinycss2                         
  - tokenizers                       
  - toml                             
  - tomli                            
  - toolz                            
  - torch                            
  - torchaudio                       
  - torchdata                        
  - torchsummary                     
  - torchtext                        
  - torchvision                      
  - tornado                          
  - tqdm                             
  - traitlets                        
  - traittypes                       
  - transformers                     
  - triton                           
  - tweepy                           
  - typer                            
  - types-pytz                       
  - types-setuptools                 
  - typing_extensions                
  - tzlocal                          
  - uc-micro-py                      
  - uritemplate                      
  - urllib3                          
  - vega-datasets                    
  - wadllib                          
  - wasabi                           
  - wcwidth                          
  - weasel                           
  - webcolors                        
  - webencodings                     
  - websocket-client                 
  - Werkzeug                         
  - wheel                            
  - widgetsnbextension               
  - wordcloud                        
  - wrapt                            
  - xarray                           
  - xarray-einstats                  
  - xgboost                          
  - xlrd                             
  - xxhash                           
  - xyzservices                      
  - yarl                             
  - yellowbrick                      
  - yfinance                         
  - zict                             
  - zipp                               

 