name:
  - DCAC
channels:
  - conda-forge
  - default
  - CogSci
dependencies:
  - conda=24.5.0
  - python=3.12.4
  - numpy
  - matplotlib
  - ipywidgets
  - nodejs
  - rpy2
  - scipy
  - datamatrix=1.0.13

