name:
  - DCAC
channels:
  - conda-forge
  - CogSci
  - anaconda
dependencies:
  - beautifulsoup4
  - blosc
  - bokeh
  - catboost
  - conda
  - conda-pack
  - dask
  - datamatrix
  - datashader
  - fastparquet
  - feather-format
  - gdown
  - gensim
  - h5py
  - html5lib
  - ipython
  - ipywidgets
  - joblib
  - jupyter
  - jupyterlab
  - lxml
  - lz4
  - matplotlib
  - networkx
  - numba
  - numpy
  - openpyxl
  - pandas
  - pillow
  - plotly
  - pyarrow
  - pygwalker
  - python
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - snappy
  - statsmodels
  - xgboost
  - xlrd
  - xlwt
  - opensesame-extension-osweb 
  - opensesame-plugin-psychopy 
  - opensesame-plugin-media_player_mpy 
  - http://files.cogsci.nl/expyriment-0.10.0+opensesame2-py3-none-any.whl
  